### ISSUE TITLE
Swagger pra gradle

### ISSUE THREAD

**Issue by kaiquepl** [Re04nan/dio-experts-spring-boot-java#1]
Renan, primeiro quero agradecer pelo conhecimento que vc compartilhou com a gente atravez da DIO.
Gostaria de saber como configuro o Swagger pra um projeto Gradle que  eu gostaria de documentar, porém, não estou achando informações muito claras sobre, e o conteudo que consegui na internet não esta funcionando por mais que eu me esforce na solução. Quero saber como posso fazer isso, incluindo as dependencias do Swagger no build,gradle. Se conseguir me ajudar eu agradeço muitissimo!

**Comment by Re04nan** [comment]
Que bom que gostou Kaique e obrigado. Para resolver esse problema de dependências no gradle, utilize o https://mvnrepository.com/ onde pode pesquisar as mesmas dependências utilizadas no Maven durante o curso e adicionar no projeto no formato apropriado. Após isso só continuar com o curso como demonstrado, me conta se conseguiu!

**Comment by kaiquepl** [comment]
Eu consegui sim, muito obrigado Renan! Deixei um stars no projeto.
